# Change these first
owner: snowdreams1006 # Your GitHub username
repo: monitor.snowdreams1006.cn # Your GitHub repository name

# Add your sites here
sites:
  - name: blog
    url: https://blog.snowdreams1006.cn
  - name: tools
    url: https://tools.snowdreams1006.cn
  - name: easy
    url: https://easy.snowdreams1006.cn
  - name: regex
    url: https://regex.snowdreams1006.cn
  - name: regex-docs
    url: https://regex-docs.snowdreams1006.cn
  - name: mermaid-editor
    url: https://mermaid-editor.snowdreams1006.cn
  - name: bark
    url: https://bark.snowdreams1006.cn
  - name: webhook
    url: https://webhook.snowdreams1006.cn
  - name: Secret Site
    url: $SECRET_SITE

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  # cname: monitor.snowdreams1006.cn
  # Uncomment the following line if you don't have a custom domain and add your repo name
  baseUrl: /monitor.snowdreams1006.cn
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: monitor.snowdreams1006.cn
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
